#!/bin/bash

echo "🚀 Magazine Website Vercel Deployment Setup"
echo "=========================================="

echo ""
echo "📋 Prerequisites Check:"
echo "1. Make sure your code is pushed to GitHub"
echo "2. Have your Vercel account ready"
echo "3. Have your environment variables ready"
echo ""

echo "🔧 Environment Variables Needed:"
echo ""
echo "Backend Variables (set in Vercel backend project):"
echo "- MONGO=your_mongodb_connection_string"
echo "- CLERK_SECRET_KEY=your_clerk_secret_key"
echo "- CLIENT_URL=your_frontend_vercel_url"
echo "- IK_YOUR_IMAGEKIT_PUBLIC_KEY=your_imagekit_public_key"
echo "- IK_YOUR_IMAGEKIT_PRIVATE_KEY=your_imagekit_private_key"
echo "- IK_YOUR_IMAGEKIT_URL_ENDPOINT=your_imagekit_url_endpoint"
echo ""
echo "Frontend Variables (set in Vercel frontend project):"
echo "- VITE_CLERK_PUBLISHABLE_KEY=your_clerk_publishable_key"
echo "- VITE_API_URL=your_backend_vercel_url"
echo ""

echo "📁 Project Structure:"
echo "├── backend/          (Deploy as separate Vercel project)"
echo "│   ├── index.js"
echo "│   ├── package.json"
echo "│   └── vercel.json"
echo "└── client/           (Deploy as separate Vercel project)"
echo "    ├── src/"
echo "    ├── package.json"
echo "    └── vercel.json"
echo ""

echo "🎯 Deployment Steps:"
echo "1. Deploy backend first (Node.js project)"
echo "2. Get the backend URL from Vercel"
echo "3. Deploy frontend (Vite project)"
echo "4. Set VITE_API_URL to your backend URL"
echo "5. Test all functionality"
echo ""

echo "✅ Configuration Files Created:"
echo "- backend/vercel.json"
echo "- client/vercel.json"
echo "- DEPLOYMENT_GUIDE.md"
echo ""

echo "🔗 Useful Links:"
echo "- Vercel Dashboard: https://vercel.com/dashboard"
echo "- Vercel Documentation: https://vercel.com/docs"
echo ""

echo "📝 Next Steps:"
echo "1. Push your code to GitHub"
echo "2. Follow the DEPLOYMENT_GUIDE.md for detailed instructions"
echo "3. Set up environment variables in Vercel"
echo "4. Deploy both projects"
echo ""

echo "🎉 Good luck with your deployment!" 